Rename publish workflow job to publish (#1)
* rename job to publish

* Upload unit test result artifact (plus failure to trigger

* renamed job to run-unit-tests

* Fix indent for continue on error

* Use newer uploader and explicitly set result

* Capture test return code

* grep output file for result

* Fix unit test

diff --git a/.github/workflows/unit_test.yml b/.github/workflows/unit_test.yml
--- a/.github/workflows/unit_test.yml
+++ b/.github/workflows/unit_test.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:  # Allows manual triggering of the workflow
 
 jobs:
-  test:
+  run-unit-tests:
     runs-on: ubuntu-latest
 
     steps:
@@ -29,4 +29,22 @@ jobs:
 
       - name: Run pytest
         run: |
-          poetry run pytest --maxfail=1 --disable-warnings -q  # Run pytest using Poetry's virtualenv
+          poetry run pytest --maxfail=1 --disable-warnings -q > test-results.txt  # Run pytest using Poetry's virtualenv
+        continue-on-error: true  # Upload even if pytest fails
+
+      - name: Upload Test Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: test-results.txt
+
+      - name: Set test status
+        run: |
+          if [[ -f test-results.txt ]]; then
+            cat test-results.txt
+            if grep -q "FAILED" test-results.txt; then
+              echo "Test failed"
+              exit 1
+            fi
+          fi
+       
